### ISSUE TITLE
게시글 사용자 정보 가져오기

### ISSUE THREAD

**Issue by DaHoon06** [DaHoon06/forYourRecipe#35]
레시피 작성이 작성자의 경우 uid로 저장하게 했습니다.

상세보기로 들어갔을 경우 **레시피와 함께 작성자에 대한 간단한 정보**를 나타내면 어떨까 합니다.

#### 필요 정보

1. 작성자 프로필
2. 작성자 닉네임
3. 작성자 소개말

---

#### sample

![Image](https://user-images.githubusercontent.com/76781436/228741226-7d697612-e8d1-4ade-b959-9618bd3b82b9.png)

**Comment by hprl** [comment]
깔끔하고 아주 맘에들어요

**Comment by hprl** [comment]
### 수정사항

admin
```
user : {
  name: 'admin'
}
```
user
```
user : {
  id: 'user id',
  name: 'user name',
  img: 'user profile img',
  introduce: 'let me introduce my self'
}
```

로 리턴됩니다.

https://github.com/DaHoon06/forYourRecipe/commit/637db27eb42eec2fb17f70ba368a70d9e134d424
